<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Standoff rod macro -->
  <xacro:macro name="standoff_rod" params="prefix x_offset y_offset">
    <!-- Constants for the rod - 20mm diameter (0.01m radius), 220mm length -->
    <xacro:property name="rod_radius" value="0.01" />
    <xacro:property name="rod_length" value="0.22" />
    <xacro:property name="rod_mass" value="0.1" />
    <xacro:property name="rod_z_offset" value="0.19" />

    <link name="${prefix}_rod_link">
      <inertial>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <mass value="${rod_mass}"/>
        <inertia 
          ixx="${rod_mass * (3*rod_radius*rod_radius + rod_length*rod_length) / 12}" 
          ixy="0" 
          ixz="0" 
          iyy="${rod_mass * (3*rod_radius*rod_radius + rod_length*rod_length) / 12}" 
          iyz="0" 
          izz="${rod_mass * rod_radius*rod_radius / 2}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rod_radius}" length="${rod_length}"/>
        </geometry>
        <material name="robot_silver"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${rod_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${rod_radius}" length="${rod_length}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_rod_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_rod_link"/>
      <origin xyz="${x_offset} ${y_offset} 0.0775" rpy="0 0 0"/>
    </joint>

    <!-- Gazebo-specific properties -->
    <gazebo reference="${prefix}_rod_link">
      <material>Gazebo/Grey</material>
    </gazebo>
  </xacro:macro>

</robot>